import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-theme="cupcake" lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="w-full h-[75px] border-2 flex justify-center">
          <div className="navbar bg-neutral text-neutral-content">
            <h1 className="text-xl font-semibold px-3 py-2 rounded hover:bg-gray-300 hover:text-black transition">Echo</h1>
          </div>
        </div>
        <div className="flex justify-center">
          {children}
          <Toaster position="top-right" />
        </div>
      </body>
    </html>
  );
}
