import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { SocketProvider } from "../app/context/SocketContext";
// @ts-ignore: side-effect import of CSS; add a global declaration file (e.g. globals.d.ts) to type CSS imports properly
import "./globals.css";
import NavBar from "./components/NavBar";
import { LoggedProvider } from "./context/logginContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-theme="cupcake" lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <LoggedProvider>
          <NavBar />
          <div className="flex justify-center">
            <SocketProvider>{children}</SocketProvider>
            <Toaster position="top-right" />
          </div>
        </LoggedProvider>
      </body>
    </html>
  );
}
